---
- name: barnyard2 | installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - libmysqlclient-dev
    - libtool
    - mysql-client
  when: ansible_os_family == "Debian"

- name: barnyard2 | cloning barnyard2 repo
  git:
    repo: "https://github.com/firnsy/barnyard2"
    dest: "/opt/barnyard2"
    update: no
