---
- name: installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - ethtool
    - flex
    - libpcap-dev
    - libpcre3-dev
    - libdumbnet-dev
    - zlib1g-dev

- name: installing snort
  apt:
    name: snort
    state: present
