---
- name: installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - ethtool
    - flex
    - iproute
    - libpcap-dev
    - libpcre3-dev
    - libdumbnet-dev
    - zlib1g-dev

- name: installing snort
  apt:
    name: snort
    state: present

- name: configuring snort daemon
  template:
    src: "etc/snort/snort.debian.conf.j2"
    dest: "/etc/snort/snort.debian.conf"
    owner: root
    group: root
    mode: 0600
  notify: restart snort
